// DATA:
export const FETCH_DATA = 'FETCH_DATA';
export const CREATE_CONTACT = 'CREATE_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';

// SESSION:
export const CHANGE_STATUS = 'CHANGE_STATUS';
